
import "./globals.css";



export const metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/favicon.ico',
    other: [
      { rel: 'icon', url: '/favicon.ico' },
      { rel: 'shortcut icon', url: '/favicon.ico', type: 'image/x-icon' },
      { rel: 'apple-touch-icon', url: '/favicon.ico' },
    ],
  },
  openGraph: {
    locale: 'en_US',
    images: [
      {
        url: '/favicon.ico',
        width: 1200,
        height: 630,
        type: 'image/png',
      },
    ],
    type: 'website',
    url: 'https://www.rolvary.in/',
    siteName: 'Rolvary',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
